### ISSUE TITLE
How to build GMQL-Docker? Missing file

### ISSUE THREAD

**Issue by cursecatcher** [DEIB-GECO/GMQL-Docker#1]
Hi, 
I am trying to build the GMQL-Docker image. In the third step of the building process, the file gmql-web-1.0-SNAPSHOT.zip is required and it is not present in the repo. 
Where can I get this file in order to properly build the image? 
Thanks in advance. 

Ps. It would be simple if you could push a functional Docker image to Docker Hub.

**Comment by lucananni93** [comment]
Hi and thanks for your interest in our project.
We are currently working on the dockerization of our software. We are aware that the Dockerfile in this repository is not functioning properly and is not updated. 

We will inform you when a proper docker is uploaded on Docker Hub.

Luca

**Comment by lucananni93** [comment]
The Docker image is now deployable following the instruction on the README.

Best,

Luca
